baseURL = "https://record.mona.cx"
locale = "zh-cn"
title = "我的记录间"
theme = "anubis2"
hasCJKLanguage = true
summaryLength = 140


[pagination]
  pagerSize = 6

[params.author]
  name = "mona"

[[menu.main]]
  identifier = "home"
  name = "首页"
  url = "/"
  weight = 1

[[menu.main]]
  identifier = "tags"
  name = "标签"
  url = "/tags/"
  weight = 2

[[menu.main]]
  name = "归档"
  identifier = "archive"
  url = "/posts/"
  weight = 3

[markup.goldmark.renderer]
  unsafe = true

[markup.highlight]
  noClasses = false
  guessSyntax = true
  style = 'github-dark'



[params.anubis2]
  enablerssicon = false
  customcss = ["css/custom.css"]
